#' Transcript Categorization With Sampling
#' 
#' This function takes the list created by one of the sep.panel() functions, and reformats it into meaningful codes, as well as reshapes the data into a melted
#' dataframe that will be supplied to ggplot. This formatting only works for making content bar charts specific to those generated by the transcriptBarChart
#' function.
#' @param data The object created by one of the sep.pane() functions
#' @keywords melt
#' @export
#' @examples 
#' content.for.plot(content.summary)



content.for.plot <- function(data) {
  library(reshape2)
  # Subset columns with present/absent codes 
  known.results <- data$KN_Results[, c(5,6)]
  ntkg.results <- data$NTKG_Results[, c(5,6)]
  ntng.results <- data$NTNG_Results[, c(5,6)]
  
  # Change codes to factor and give meaningful labels for both known and novel datasets
  known.results[, 1] <- factor(known.results[, 1], levels = c(2,6,11,15), labels = c("Present in both", "Present in ALO IB", "Present in ALO RI", "Not present"), ordered = FALSE)
  known.results[, 2] <- factor(known.results[, 2], levels = c(2,6,11,15), labels = c("Present in all strains", "Present in all IB", "Present all RI", "Other"), ordered = FALSE)
  
  ntkg.results[, 1] <- factor(ntkg.results[, 1], levels = c(2,6,11,15), labels = c("Present in both", "Present in ALO IB", "Present in ALO RI", "Not present"), ordered = FALSE)
  ntkg.results[, 2] <- factor(ntkg.results[, 2], levels = c(2,6,11,15), labels = c("Present in all strains", "Present in all IB", "Present all RI", "Other"), ordered = FALSE)
  
  ntng.results[, 1] <- factor(ntng.results[, 1], levels = c(2,6,11,15), labels = c("Present in both", "Present in ALO IB", "Present in ALO RI", "Not present"), ordered = FALSE)
  ntng.results[, 2] <- factor(ntng.results[, 2], levels = c(2,6,11,15), labels = c("Present in all strains", "Present in all IB", "Present all RI", "Other"), ordered = FALSE)
  # summarize content totals for "at least one" data
  freq.known <- table(known.results$RS.atleast1)
  freq.ntkg <- table(ntkg.results$RS.atleast1)
  freq.ntng <- table(ntng.results$RS.atleast1)
  freq.comb <- rbind(freq.known, freq.ntkg, freq.ntng)
  
  # Prepare ALO data for plot
  Names=c("Known", "NTKG", "NTNG")     # create list of names
  forPlot.alo <- data.frame(Names, cbind(freq.comb))   # combine them into a data frame
  
  # melt the data frame for plotting
  forPlot.alo.m <- melt(forPlot.alo, id.vars='Names')
  
  # Make datasubset without "not present"
  forPlot.alo.m2 <- forPlot.alo.m[-c(10, 11, 12), ]
  
  # summarize content totals for "in all" data
  freq.known.tot <- table(known.results$RS.all)
  freq.ntkg.tot <- table(ntkg.results$RS.all)
  freq.ntng.tot <- table(ntng.results$RS.all)
  freq.comb.tot <- rbind(freq.known.tot, freq.ntkg.tot, freq.ntng.tot)
  
  # Prepare ALO data for plot
  Names=c("Known", "NTKG", "NTNG")     # create list of names
  forPlot.tot <- data.frame(Names, cbind(freq.comb.tot))   # combine them into a data frame
  
  # melt the data frame for plotting
  forPlot.tot.m <- melt(forPlot.tot, id.vars='Names')
  
  # Make datasubset without "other"
  forPlot.tot.m2 <- forPlot.tot.m[-c(10, 11, 12), ]
  return(list("ALO.ForPlot" = forPlot.alo.m, "ALO.ForPlotSS" = forPlot.alo.m2, "ALL.ForPlot" = forPlot.tot.m, "ALL.ForPlotSS" = forPlot.tot.m2, "NTKG.results" = ntkg.results, "NTNG.results" = ntng.results, "Known.results" = known.results))
}